[project]
name = "trackstar-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yuvraj Sabale", email = "yuvrajsabale999@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=4.0.11",
]

[project.scripts]
trackstar-mcp = "trackstar_mcp:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
